# Generated by Django 3.2.18 on 2023-05-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anno', models.DateField(max_length=255)),
                ('Marca', models.TextField(max_length=255)),
                ('Color', models.TextField(max_length=255)),
                ('Combustible', models.TextField(max_length=255)),
                ('NumPuertas', models.TextField(max_length=255)),
                ('Traccion', models.TextField(max_length=255)),
            ],
        ),
    ]
